### ISSUE TITLE
Class 'Softerize\Tablelize\TablelizeServiceProvider' not found

### ISSUE THREAD

**Issue by amviro** [softerize/tablelize#1]
Hello,

I'm getting the following error after adding provider.
`Class 'Softerize\Tablelize\TablelizeServiceProvider' not found`

Regards

**Comment by oscardias** [comment]
Hi @dinajpuri ,

You were faster than me when you tested it... I missed the composer autoload section.
Please do a `composer update` in order to get version 0.1.1 and it will fix the problem.

Cheers

**Comment by amviro** [comment]
The error is fixed with the update
