### ISSUE TITLE
How to manipulate column data output?

### ISSUE THREAD

**Issue by amviro** [softerize/tablelize#2]
Hi @oscardias,

I'm trying to link Post titles to their details page. 
Could you pls give me some hint how to do so?

Regards

**Comment by oscardias** [comment]
Hi @dinajpuri ,

Currently the only way to manipulate the output and create a link is by using a method in your model. Something like this:

**Posts Model**

``` php
public function getLink($title) {
    // The value of the field will be passed as the parameter, but you could also use $this->title
    return '<a href="' . url('posts/view/', $this->id).'">'.$title.'</a>';
}
```

When you call tablelize, you'll need to use the following options:

``` php
$options = [
        'idField' => 'id',
        'fields' => [
            [
                'name' => 'title',
                'label' => 'Post Title',
                'method' => 'getLink',
                'escape' => false // Prevent value escaping because it has HTML
            ],
            // Add other fields as desired
        ],
        'rowActions' => [
            [
                'url'  => 'view',
                'icon' => 'glyphicon glyphicon-search',
                'text' => 'View Post'
            ]
        ]
    ];
```

The rowActions property will generate a link using `url()` and will send the table id as a parameter. If your ID field is different than `id`, you can also set the `idField` option to whatever you're using.
